---
name: actionlint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Lint with actionlint
        uses: reviewdog/action-actionlint@31863360b75778136a7171692ecf0fe26fb5d630
