---
name: golangci-lint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5
