---
name: golangci-lint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29
